version: '3.5'
services:
    database:
        image: 
            mongo-image:v1 
        container_name: 'booking_db'
        volumes:
            - ./booking-volume:/data/db
        ports:
            - '27017-27019:27017-27019'

    clients-service: 
        image: 
            clients-service:v1
        container_name: 'booking_clients'
        command: go run ./cmd/clients/main.go
        depends_on:
            - database

    rooms-service: 
        image: 
            rooms-service:v1
        container_name: 'booking_rooms'
        command: go run ./cmd/rooms/main.go
        depends_on:
            - database

    server-service: 
        image: 
            server-service:v1
        container_name: 'booking_server'
        command: go run ./cmd/server/main.go
        depends_on:
            - clients-service
            - rooms-service